### ISSUE TITLE
Arrow rotation not working for length=0

### ISSUE THREAD

**Issue by JoachimGoedhart** [DaetwylerStephan/draw_arrow_in_movies#2]
When the arrow length is set to zero, the angle that is used for drawing is zero, also when you set it to different values.
(To solve this for my case, I set the length to 1)

**Comment by DaetwylerStephan** [comment]
Indeed, setting the arrow length to 1 is required to get the proper orientation (based on how the plugin internally calculates the arrow orientation). Thank you for pointing this out! In a future release, I will handle this issue with a minimal length of 1 required. Having an arrow length of 1 should not limit any design choice of the custom shape.
